FROM node:16 AS builder
WORKDIR /usr/src/app
RUN npm -v
RUN npm install -g npm@8.5.0
RUN npm -v
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:16-alpine AS prod
# RUN apk update; apk add --no-cache curl
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app .
RUN chown node:node -R /usr/src/app/dist
USER node
EXPOSE 3000
CMD [ "npm", "run", "start:prod" ]