version: "3"

services:
  database:
    container_name: siomay_postgre
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: ${DB_TZ}
    ports:
        - 5432:5432
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - api
    restart: always
  # app:
  #   env_file:
  #     - .env
  #   container_name: siomay_api
  #   image: siomayapp/siomay-api:latest
  #   environment:
  #     TZ: Asia/Jakarta
  #   restart: unless-stopped
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - database
  #   working_dir: /usr/src/app
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   command: npm run start:prod
  #   networks:
  #     - api
  #   links:
  #     - database
volumes:
  data:
    driver: local
networks:
  api:
    driver: bridge
