# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Siomay App CI/CD

on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm i
    - run: npm run build --if-present
    - run: npm run test

    - name: Create .env file
      run: |
        touch .env
        echo PORT=3000 >> .env
        
        echo DB_TYPE=postgres >> .env
        echo DB_HOST=${{ secrets.DB_HOST }} >> .env
        echo DB_PORT=${{ secrets.DB_PORT }} >> .env
        echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env
        echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
        echo DB_NAME=${{ secrets.DB_NAME }} >> .env
        echo DB_TZ=Asia/Jakarta >> .env

        echo JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} >> .env

        echo SESSION_SECRET=${{ secrets.SESSION_SECRET }} >> .env

        echo REDIS_HOST=${{ secrets.REDIS_HOST }} >> .env
        echo REDIS_PORT=${{ secrets.REDIS_PORT }} >> .env
        echo REDIS_TTL=60 >> .env

        echo SEED_OWNER_NAME=${{ secrets.SEED_OWNER_NAME }} >> .env
        echo SEED_OWNER_USERNAME=${{ secrets.SEED_OWNER_USERNAME }} >> .env
        echo SEED_OWNER_PASSWORD=${{ secrets.SEED_OWNER_PASSWORD }} >> .env
        echo SEED_OWNER_PHONE=${{ secrets.SEED_OWNER_PHONE }} >> .env

    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/siomay-api:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/siomay-api:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/siomay-api:buildcache,mode=max
